# Site settings
title: bigdata Blog
header-img: img/home-bg.jpg
email: along322@163.com
copyright_name: Your/Project/Corporate Name
description: "hello body welcome to iamwljiang's blog!!"
baseurl: ""
url: "https://iamwljiang.github.org"
twitter_username: 
github_username:  iamwljiang
facebook_username:  
email_username:  along322@163.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
